name: Cypress Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' 

jobs:
  cypress-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in Chrome (1920x1080)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true
          spec: cypress/e2e/**/*.feature
          config: viewportWidth=1920,viewportHeight=1080
          config-file: cypress.config.js

      - name: Run Cypress tests in Chrome (1366x768)
        if: success() 
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true
          spec: cypress/e2e/**/*.feature
          config: viewportWidth=1366,viewportHeight=768
          config-file: cypress.config.js

      - name: Upload Mochawesome reports (Chrome)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-reports-chrome
          path: cypress/reports/*.json

      - name: Upload Screenshots (Chrome)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots/

  cypress-firefox:
    runs-on: ubuntu-latest
    needs: cypress-chrome 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in Firefox (1920x1080)
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          headed: true
          spec: cypress/e2e/**/*.feature
          config: viewportWidth=1920,viewportHeight=1080
          config-file: cypress.config.js

      - name: Run Cypress tests in Firefox (1366x768)
        if: success()
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          headed: true
          spec: cypress/e2e/**/*.feature
          config: viewportWidth=1366,viewportHeight=768
          config-file: cypress.config.js

      - name: Upload Mochawesome reports (Firefox)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-reports-firefox
          path: cypress/reports/*.json

      - name: Upload Screenshots (Firefox)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-firefox
          path: cypress/screenshots/